version: '3.8'

services:
  # Application service
  v5:
    build: ./
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=petclinic
    ports:
      - "8080:8080"  # Expose application port
    depends_on:
      - mydb  # Ensure database service is started first

  # Database service
  mydb:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_ROOT_PASSWORD=petclinic 
    ports:
      - "3306:3306"  # Expose database port
